### ISSUE TITLE
Draw crosshairs don't revert to hand upon cancel

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-factfinder#292] opened 2017-12-08 15:36 UTC
If you click the draw button to enter drawing mode, then click it again to end drawing mode, the default cursor remains crosshairs. When drawing mode ends, the cursor default should revert back to hand.

**Comment by chriswhong** [comment] 2018-01-02 21:04
Went down a rabbithole on this one.  I confirmed that the draw control is being removed from the map, and my assumption is that mapbox-gl-draw doesn't want to ever be removed (but we have to manually remove it due to another bug where it intercepts touch interactions on mobile) 

Adding `help-wanted` tag, but I don't think this is high priority.

**Comment by allthesignals** [comment] 2020-03-05 01:40
I think this is fixed. Closing.

**Closed by allthesignals** 2020-03-05 01:40 UTC
Labels: Luxury
