### ISSUE TITLE
Email icon in header does not function

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-factfinder#661] opened 2019-01-07 15:39 UTC

**Comment by hannahkates** [comment] 2019-01-07 18:21
If you right click on the email icon and say "open in a new tab" the mailto link is valid and does work, so the problem is that clicking the icon doesn't actually open the link. I also checked to make sure it wasn't a browser handler setting issue -- the mailto link on About page does open immediately. 

This seems likely an problem with the new object type that houses the nav bar items since labs-ui is integrated.  I attempted the solution target="_top" given here (https://stackoverflow.com/a/26150427) for hrefs inside iframes, but it didn't fix the problem.

**Comment by hannahkates** [comment] 2019-01-07 19:35
This issue will be addressed in changes to labs-ui, since the action on the container is preventing the default behavior of the link
https://github.com/NYCPlanning/labs-ui/blob/develop/addon/templates/components/labs-ui/site-header.hbs#L16

**Closed** 2019-01-08 21:15 UTC
Labels: bug, review
